### PR TITLE
Combine fetch source and prepare resources in EVG config.yml

### PR DESCRIPTION
**Pull request by Jibola**

### CODE REVIEW

**Comment by blink1073** [comment]
This is hard to review because of the yaml reformatter.  Can we do that as a separate PR so we can add it to git-blame-ignore-revs?

**Comment by Jibola** [comment]
> This is hard to review because of the yaml reformatter. Can we do that as a separate PR so we can add it to git-blame-ignore-revs?

Whoops. Thanks for pointing that out. Didn't mean to place in the autoformatting.

**Comment by blink1073** [comment]
> Please set the PROJECT_DIRECTORY environment variable.

**Comment by blink1073** [comment]
There is a merge conflict

**Comment by blink1073** [comment]
It looks like UPLOAD_BUCKET isn't being set properly, maybe add some debug logging?

**Comment by Jibola** [comment]
need to remove additional calls to `prepare resources`

**Review by blink1073 — APPROVED** [review]
LGTM!

**Pull request merged**
