### PR TITLE
Address build failures due to Python 3 binary lookup

### PR DESCRIPTION
**Pull request by eramongodb**
Partially reverts some changes made in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/352 concerning Python 3 binary lookup (motivated by [a stray explicit call to `python`](https://github.com/mongodb-labs/drivers-evergreen-tools/commit/f825f86fae3e5eecfa5da05a510ec5962fc7de88#diff-5eb412fc2cdeb6fab58a38e622949bedbda012b8bcb61e5e6daec62e5168af87L101)) to address build failures on some EVG distros where neither `python` nor `python3` are available in default binary paths.

The `Using Python3 binary: $PYTHON` case added in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/352 is preserved to avoid a redundant call to `find_python3` when `start-orchestration.sh` is invoked via `run-orchestration.sh` (which already called `find_python3`). This _might_ still break EVG builds that happen to set the `PYTHON` environment variable before invoking `start-orchestration.sh` directly (instead of through `run-orchestration.sh`) if `PYTHON` is set to a Python binary that is not 3.0+ or does not support venv. If that is the case, this too can be reverted to the prior unconditional call to `find_python3`.

### CODE REVIEW

**Comment by blink1073** [comment]
Test failure: `find-python3.sh must be run in a Bash shell!`

**Review by blink1073 — APPROVED** [review]
LGTM, thanks!

**Review by jmikola — APPROVED** [review]

**Comment by eramongodb** [comment]
Although the GitHub Actions config was updated to use `shell: bash` for consistency, the `run-orchestration.sh` script itself still uses `#!/bin/sh` for backwards-compatibility, as many DET users still run `sh run-orchestration.sh`. Making `run-orchestration.sh` require Bash would be a change far beyond the scope of this PR; therefore, a Bash subshell is used to run `find_python3` instead. Documented this context with a comment prior to running `find_python3`.

**Comment by blink1073** [comment]
Test failure is unrelated, was fixed in #356

**Pull request merged**
