### PR TITLE
DRIVERS-2991 Prefer lsof over fuser for macos support

### PR DESCRIPTION
**Pull request by ShaneHarvey**
DRIVERS-2991 Prefer lsof over fuser for macos support.

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
Testing: https://spruce.mongodb.com/version/66f5dcc6aac4f70007254d1d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

**Comment by blink1073** [comment]
Does this supersede #507?

**Comment by blink1073** [comment]
Maybe try pinning pymongo<4.9?

**Comment by ShaneHarvey** [comment]
Neglected to add an update here on my progress from yesterday. I was hoping that the original commit would fix it but I saw the replSetInitiate errors Neal pointed out above. 

I'm testing a new approach which sends SIGTERM to 8889 and other common mongodb server ports used by MO: https://spruce.mongodb.com/version/66f6e7d69dd7c000079c1191/

**Comment by nbbeeken** [comment]
thanks so much for staying on top of this!!!

I already restarted: [spruce.mongodb.com/version/66f6c8986b942e0007c938e7](https://spruce.mongodb.com/version/66f6c8986b942e0007c938e7) which will pull this new commit

some of the logs are showing up and we're making it past mongo-orch on win, linux, and mac 🎉 🤞🏻

**Review by nbbeeken — APPROVED** [review]
LGTM, I've clicked through enough CI tasks to see they're all getting passed setup

update: all green 💚

**Pull request merged**
