### PR TITLE
DRIVERS-1771: Add 5.0 release

### PR DESCRIPTION
**Pull request by jyemin**

### CODE REVIEW

**Comment by jyemin** [comment]
It looks like there is some testing in https://github.com/mongodb-labs/drivers-evergreen-tools/blame/master/.evergreen/config.yml, but it hasn't been maintained

**Comment by jmikola** [comment]
> It looks like there is some testing in https://github.com/mongodb-labs/drivers-evergreen-tools/blame/master/.evergreen/config.yml, but it hasn't been maintained

Not sure what you're referring to in there, but I'd suggest either creating a ticket to either remove the unmaintained bits or bring them up to speed so we can actually use them.

**Comment by alcaeus** [comment]
Filed [DRIVERS-1771](https://jira.mongodb.org/browse/DRIVERS-1771) to track this effort.

**Review by alcaeus — APPROVED** [review]

**Comment by alcaeus** [comment]
> Not sure what you're referring to in there, but I'd suggest either creating a ticket to either remove the unmaintained bits or bring them up to speed so we can actually use them.

[DRVIERS-1772](https://jira.mongodb.org/browse/DRIVERS-1772)

**Pull request merged**
