### PR TITLE
Start shards as three member replica sets.

### LINKED ISSUE #24: The default configuration for shards should use a three member replica set
Currently the shards are configured with a single member replica set.  This was a recent change from using standalones.  But this causes some tests of secondary reads to fail because there is no secondary for mongos to read from.  

So let's use a three member replica set, which is what our users are going to be doing anyway at a minimum.

### PR DESCRIPTION
**Pull request by ShaneHarvey**
Resolves #24.

Evergreen: https://evergreen.mongodb.com/version/5a020a83e3c3316365000399

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
I reverted this change because it is causing test failures in the Java driver.

**Comment by jyemin** [comment]
It's looking good now, so please un-revert.

**Comment by ShaneHarvey** [comment]
Waiting for a Python patch build to succeed just in case: https://evergreen.mongodb.com/version/5a0376212a60ed22a2009962

**Comment by ShaneHarvey** [comment]
Looks like this commit breaks the latest_sharded_cluster task on Windows: https://evergreen.mongodb.com/version/5a020a83e3c3316365000399

**Comment by ShaneHarvey** [comment]
@jyemin I looked into to the failures for a few minutes but can't make any sense of them. Looks like it only breaks Windows latest sharded cluster with authentication. Here are some snippets from the logs:

mongos port 27017:
```
2017-11-08T22:35:52.162+0000 I NETWORK  [shard registry reload] Starting new replica set monitor for 13f3804c-886f-4dd2-a0b6-6ff77bf2aa48/localhost:27117,localhost:27118
2017-11-08T22:35:52.163+0000 I NETWORK  [shard registry reload] Starting new replica set monitor for 18a58bb2-e683-40dd-a370-e06c61d2ff6b/localhost:27217,localhost:27218
2017-11-08T22:35:52.165+0000 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] can't authenticate to localhost:27117 (127.0.0.1) as internal user, error: Authentication failed.
2017-11-08T22:35:52.165+0000 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:1026, took 1005ms (3 connections now open to localhost:1026)
2017-11-08T22:35:52.166+0000 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: LockStateChangeFailed: findAndModify query predicate didn't match any lock document
```
Config server port 1026
```
2017-11-08T22:35:53.819+0000 I NETWORK  [conn26] received client metadata from 127.0.0.1:51486 conn: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.6.0-rc3-29-g1df38e1" }, os: { type: "Windows", name: "Microsoft Windows Server 2008 R2", architecture: "x86_64", version: "6.1 SP1 (build 7601)" } }
2017-11-08T22:35:53.820+0000 I NETWORK  [conn27] received client metadata from 127.0.0.1:51485 conn: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.6.0-rc3-29-g1df38e1" }, os: { type: "Windows", name: "Microsoft Windows Server 2008 R2", architecture: "x86_64", version: "6.1 SP1 (build 7601)" } }
2017-11-08T22:35:53.820+0000 I ACCESS   [conn26] Unauthorized: not authorized on admin to execute command { find: "system.keys", filter: { purpose: "HMAC", expiresAt: { $gt: Timestamp 0|0 } }, sort: { expiresAt: 1 }, readConcern: { level: "majority", afterOpTime: { ts: Timestamp 1510180517000|7, t: 1 } }, maxTimeMS: 30000, $readPreference: { mode: "nearest" }, $replData: 1, $clusterTime: { clusterTime: Timestamp 1510180551000|1, signature: { hash: BinData(0, 0000000000000000000000000000000000000000), keyId: 0 } }, $configServerState: { opTime: { ts: Timestamp 1510180517000|7, t: 1 } }, $db: "admin" }
2017-11-08T22:35:53.821+0000 I ACCESS   [conn26] Unauthorized: not authorized on config to execute command { findAndModify: "lockpings", query: { _id: "WIN-8GUQIEH1HV9:27117:1510180490:-5812933158133489990" }, update: { $set: { ping: new Date(1510180553130) } }, upsert: true, writeConcern: { w: "majority", wtimeout: 15000 }, maxTimeMS: 30000, $replData: 1, $clusterTime: { clusterTime: Timestamp 1510180551000|1, signature: { hash: BinData(0, 0000000000000000000000000000000000000000), keyId: 0 } }, $configServerState: { opTime: { ts: Timestamp 1510180517000|7, t: 1 } }, $db: "config" }
```

mongod port 27017:
```
2017-11-08T22:36:33.620+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:51621 #4 (1 connection now open)
2017-11-08T22:36:33.620+0000 I NETWORK  [conn4] received client metadata from 127.0.0.1:51621 conn: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.6.0-rc3-29-g1df38e1" }, os: { type: "Windows", name: "Microsoft Windows Server 2008 R2", architecture: "x86_64", version: "6.1 SP1 (build 7601)" } }
2017-11-08T22:36:33.621+0000 I ACCESS   [conn4] Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "13f3804c-886f-4dd2-a0b6-6ff77bf2aa48", configVersion: 1, from: "localhost:27119", fromId: 2, term: 2, $replData: 1, $db: "admin" }
```

**Comment by jyemin** [comment]
I don't want us to spend any more time on this now,  so I'll just disable that failing java driver test for sharded clusters.

**Pull request merged**
